//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTrackingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeTrackingDBEntities : DbContext
    {
        public EmployeeTrackingDBEntities()
            : base("name=EmployeeTrackingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Department> T_Department { get; set; }
        public DbSet<T_Logging> T_Logging { get; set; }
        public DbSet<T_Plan> T_Plan { get; set; }
        public DbSet<T_StaffMaster> T_StaffMaster { get; set; }
    }
}
