//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTrackingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeTrackingDBEntities : DbContext
    {
        public EmployeeTrackingDBEntities()
            : base("name=EmployeeTrackingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Department> T_Department { get; set; }
        public DbSet<T_Logging> T_Logging { get; set; }
        public DbSet<T_Plan> T_Plan { get; set; }
        public DbSet<T_StaffMaster> T_StaffMaster { get; set; }
    }
}
