//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Plan
    {
        public int PlanID { get; set; }
        public string StaffCD { get; set; }
        public System.DateTime PlanDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
    }
}
