<<<<<<< HEAD
=======
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
>>>>>>> origin/main

namespace EmployeeTrackingSystem.Models
{
    using System;
    using System.Collections.Generic;
<<<<<<< HEAD
    using System.ComponentModel.DataAnnotations;
    public partial class T_StaffMaster
    {
        [Required(ErrorMessage = "スタッフCDは必須です")]
        [StringLength(5, MinimumLength = 3, ErrorMessage = "Staff Code must be between 3 and 5 characters")]  
        public string StaffCD { get; set; }

        [Required(ErrorMessage = "スタッフ名は必須です")]
        [MaxLength(100, ErrorMessage = "スタッフ名は100文字以内です")]
        public string StaffName { get; set; }

        [Required(ErrorMessage = "スタッフCDは必須です")]
        public string DepartmentCD { get; set; }

        [MaxLength(20, ErrorMessage = "スタッフ名は100文字以内です")]
        public string Position { get; set; }

        [EmailAddress(ErrorMessage = "正しいメール形式を入力してください")]
        public string Email { get; set; }

        [MaxLength(15, ErrorMessage = "スタッフ名は100文字以内です")]
        public string PhoneNo { get; set; }

        public Nullable<System.DateTime> JoinedDate { get; set; }
        public string EmployeeType { get; set; }
        public bool Enroll { get; set; }

        [MaxLength(200, ErrorMessage = "スタッフ名は100文字以内です")]
=======
    
    public partial class T_StaffMaster
    {
        public string StaffCD { get; set; }
        public string StaffName { get; set; }
        public string DepartmentCD { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> JoinedDate { get; set; }
        public string EmployeeType { get; set; }
        public bool Enroll { get; set; }
>>>>>>> origin/main
        public string Remark { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> ReturnDateTime { get; set; }
        public string Note { get; set; }
<<<<<<< HEAD

        [RegularExpression(@"^[0-9]+$", ErrorMessage = "SeatNo must be numbers only")]
=======
>>>>>>> origin/main
        public Nullable<int> SeatNo { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
    }
}
